configMapGenerator:
- files:
  - application.yml
  name: 82230457-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ce82230457acr.azurecr.io/82230457
  newTag: "202410140953"
